# Generated by Django 5.2.12 on 2026-04-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0009_fix_fields_add_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregister_model',
            name='profile_image',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
